In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
b.dtype

dtype('float64')

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
a.itemsize

4

In [12]:
# size of b
b.itemsize

8

In [13]:
#number of elements
a.size

3

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a[1, 5]

13

In [16]:
a[0, :]


array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:, 2]

array([ 3, 10])

In [19]:
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
b[0,1,1]

4

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [25]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
np.random.rand(4,2)

array([[0.73140864, 0.67684834],
       [0.86117829, 0.24346729],
       [0.59733635, 0.28327512],
       [0.36300464, 0.1118555 ]])

In [28]:
np.random.randint(-4,8, size=(3,3))

array([[ 5,  2,  4],
       [ 3,  3,  1],
       [-1,  5, -3]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
a * 2

array([2, 4, 6, 8])

In [40]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [44]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats, axis=1)

array([3, 6])

In [49]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [50]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [56]:
a = np.array([[1,2,3,4],[8,9,10,11]])
b= np.array([[1,2,3,4], [1,2,3,4]])
np.divide(a,b)

array([[1.        , 1.        , 1.        , 1.        ],
       [8.        , 4.5       , 3.33333333, 2.75      ]])