In [1]:
import numpy as np

1.26.1


Extract all odd numbers from array

In [4]:
arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [5]:
arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Replace all odd numbers in arr with -1 without changing arr

In [8]:
arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array', out)
print('\nOriginal Array', arr)

Modified Array [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array [0 1 2 3 4 5 6 7 8 9]


Convert a 1D array to a 2D array with 2 rows

In [9]:
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Stack arrays a and b vertically

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Generate custom sequences in numpy without hardcoding

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

From array a remove all items present in array b

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

Get the positions where elements of a and b match

In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

Get all items between 5 and 10 from a.

In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])